# Generated by Django 6.0.5 on 2026-05-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_companyinfo_faq_newsarticle_promocode_ticketprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='image',
            field=models.FileField(blank=True, default='12.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='guide',
            name='photo',
            field=models.FileField(blank=True, default='a.jpg', upload_to=''),
        ),
    ]
