# Generated by Django 6.0.5 on 2026-05-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_alter_exhibit_image_alter_guide_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
