# Generated by Django 6.0.5 on 2026-05-27 13:04

import museum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_exhibit_assigned_guide_guide_hall_guide_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[museum.models.validate_age_18_plus], verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[museum.models.validate_age_18_plus], verbose_name='Дата рождения'),
        ),
    ]
