# Generated by Django 6.0.5 on 2026-05-27 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_guide_birth_date_visitor_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='child_visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_as_child', to='museum.visitor', verbose_name='Ребенок'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена билета'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='visitor_type',
            field=models.CharField(choices=[('adult', 'Взрослый'), ('child', 'Ребенок/школьник')], default='adult', max_length=10, verbose_name='Тип посетителя'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='museum.visitor', verbose_name='Дети'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='is_parent',
            field=models.BooleanField(default=False, verbose_name='Законный представитель'),
        ),
    ]
