# Generated by Django 6.0.5 on 2026-05-27 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0007_ticket_child_visitor_ticket_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='children',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='is_adult_only',
            field=models.BooleanField(default=False, verbose_name='Только для 18+'),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='museum.visitor')),
            ],
        ),
    ]
